name: Delete Old Branches

on:
  schedule:
    # Runs every day at 14:45 PM
    - cron: '45 14 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow
  
jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get install git

      - name: Fetch all branches
        run: git fetch --all --prune

      - name: Delete branches older than 1 year
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure token with 'repo' scope
        run: |
          git remote set-url originhttps://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          
          # Loop through the branches older than 1 year
          for branch in $(git for-each-ref --sort=-committerdate refs/remotes --format='%(refname:short) %(committerdate:relative)' | grep -E 'year|years ago' | awk '{print $1}'); do
            # Exclude the master branch
            if [[ $branch != "origin/master" ]]; then
              git push origin --delete ${branch#origin/}
              echo "Deleted branch: $branch"
            fi
          done
